// <auto-generated />
using System;
using Catalog.Infrastructure.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Infrastructure.EntityFramework.Migrations.Write
{
    [DbContext(typeof(WriteDbContext))]
    partial class WriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Domain.Model.Alimentos.Alimento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedAt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isDeleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nombre");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("integer")
                        .HasColumnName("unidadMedida");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("Alimento", (string)null);
                });

            modelBuilder.Entity("Catalog.Domain.Model.PlanesAlimentarios.DiaDelPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedAt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isDeleted");

                    b.Property<int>("NumeroDia")
                        .HasColumnType("integer")
                        .HasColumnName("numeroDia");

                    b.Property<Guid?>("PlanAlimentarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("PlanAlimentarioId");

                    b.ToTable("DiaDelPlan", (string)null);
                });

            modelBuilder.Entity("Catalog.Domain.Model.PlanesAlimentarios.PlanAlimentario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ComidasPorDia")
                        .HasColumnType("integer")
                        .HasColumnName("comidasPorDia");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedAt");

                    b.Property<string>("Duracion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("duracion");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isDeleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("PlanAlimentario", (string)null);
                });

            modelBuilder.Entity("Catalog.Domain.Model.PlanesAlimentarios.TiempoDeComida", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedAt");

                    b.Property<Guid?>("DiaDelPlanId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isDeleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("DiaDelPlanId");

                    b.ToTable("TiempoDeComida", (string)null);
                });

            modelBuilder.Entity("Catalog.Domain.Model.Recetas.Receta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedAt");

                    b.Property<string>("Instrucciones")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("instrucciones");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isDeleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("Receta", (string)null);
                });

            modelBuilder.Entity("Catalog.Domain.Model.Alimentos.Alimento", b =>
                {
                    b.OwnsOne("Catalog.Domain.ValueObjects.InfoNutricional", "InfoNutricionalBase", b1 =>
                        {
                            b1.Property<Guid>("AlimentoId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Calorias")
                                .HasPrecision(12, 4)
                                .HasColumnType("numeric(12,4)")
                                .HasColumnName("calorias");

                            b1.Property<decimal>("Cantidad")
                                .HasPrecision(12, 4)
                                .HasColumnType("numeric(12,4)")
                                .HasColumnName("cantidad");

                            b1.Property<decimal>("Carbohidratos")
                                .HasPrecision(12, 4)
                                .HasColumnType("numeric(12,4)")
                                .HasColumnName("carbohidratos");

                            b1.Property<decimal>("Grasas")
                                .HasPrecision(12, 4)
                                .HasColumnType("numeric(12,4)")
                                .HasColumnName("grasas");

                            b1.Property<decimal>("Proteinas")
                                .HasPrecision(12, 4)
                                .HasColumnType("numeric(12,4)")
                                .HasColumnName("proteinas");

                            b1.HasKey("AlimentoId");

                            b1.ToTable("Alimento");

                            b1.WithOwner()
                                .HasForeignKey("AlimentoId");
                        });

                    b.Navigation("InfoNutricionalBase")
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Domain.Model.PlanesAlimentarios.DiaDelPlan", b =>
                {
                    b.HasOne("Catalog.Domain.Model.PlanesAlimentarios.PlanAlimentario", null)
                        .WithMany("_diasDelPlan")
                        .HasForeignKey("PlanAlimentarioId");
                });

            modelBuilder.Entity("Catalog.Domain.Model.PlanesAlimentarios.TiempoDeComida", b =>
                {
                    b.HasOne("Catalog.Domain.Model.PlanesAlimentarios.DiaDelPlan", null)
                        .WithMany("_tiemposDeComida")
                        .HasForeignKey("DiaDelPlanId");

                    b.OwnsMany("Catalog.Domain.Model.PlanesAlimentarios.AsignacionReceta", "_recetasAsignadas", b1 =>
                        {
                            b1.Property<Guid>("TiempoDeComidaId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("RecetaId")
                                .HasColumnType("uuid")
                                .HasColumnName("recetaId");

                            b1.HasKey("TiempoDeComidaId", "Id");

                            b1.ToTable("AsignacionReceta");

                            b1.WithOwner()
                                .HasForeignKey("TiempoDeComidaId");

                            b1.OwnsOne("Catalog.Domain.ValueObjects.Racion", "Racion", b2 =>
                                {
                                    b2.Property<Guid>("AsignacionRecetaTiempoDeComidaId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("AsignacionRecetaId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Cantidad")
                                        .HasColumnType("integer")
                                        .HasColumnName("racionCantidad");

                                    b2.HasKey("AsignacionRecetaTiempoDeComidaId", "AsignacionRecetaId");

                                    b2.ToTable("AsignacionReceta");

                                    b2.WithOwner()
                                        .HasForeignKey("AsignacionRecetaTiempoDeComidaId", "AsignacionRecetaId");
                                });

                            b1.Navigation("Racion")
                                .IsRequired();
                        });

                    b.Navigation("_recetasAsignadas");
                });

            modelBuilder.Entity("Catalog.Domain.Model.Recetas.Receta", b =>
                {
                    b.OwnsMany("Catalog.Domain.Model.Recetas.IngredienteReceta", "_ingredientes", b1 =>
                        {
                            b1.Property<Guid>("RecetaId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AlimentoId")
                                .HasColumnType("uuid")
                                .HasColumnName("alimentoId");

                            b1.HasKey("RecetaId", "Id");

                            b1.ToTable("IngredienteReceta");

                            b1.WithOwner()
                                .HasForeignKey("RecetaId");

                            b1.OwnsOne("Catalog.Domain.ValueObjects.Porcion", "Porcion", b2 =>
                                {
                                    b2.Property<Guid>("IngredienteRecetaRecetaId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("IngredienteRecetaId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Cantidad")
                                        .HasPrecision(12, 4)
                                        .HasColumnType("numeric(12,4)")
                                        .HasColumnName("porcionCantidad");

                                    b2.HasKey("IngredienteRecetaRecetaId", "IngredienteRecetaId");

                                    b2.ToTable("IngredienteReceta");

                                    b2.WithOwner()
                                        .HasForeignKey("IngredienteRecetaRecetaId", "IngredienteRecetaId");
                                });

                            b1.Navigation("Porcion")
                                .IsRequired();
                        });

                    b.Navigation("_ingredientes");
                });

            modelBuilder.Entity("Catalog.Domain.Model.PlanesAlimentarios.DiaDelPlan", b =>
                {
                    b.Navigation("_tiemposDeComida");
                });

            modelBuilder.Entity("Catalog.Domain.Model.PlanesAlimentarios.PlanAlimentario", b =>
                {
                    b.Navigation("_diasDelPlan");
                });
#pragma warning restore 612, 618
        }
    }
}
