// <auto-generated />
using System;
using Catalog.Infrastructure.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Infrastructure.EntityFramework.Migrations.Read
{
    [DbContext(typeof(ReadDbContext))]
    [Migration("20260813203718_InitialReadDbContext")]
    partial class InitialReadDbContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.2.25163.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Infrastructure.EntityFramework.ReadModel.Alimento.AlimentoReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Calorias")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("calorias");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("Carbohidratos")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("carbohidratos");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedAt");

                    b.Property<decimal>("Grasas")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("grasas");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isDeleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Proteinas")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("proteinas");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("integer")
                        .HasColumnName("unidadMedida");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("Alimento", (string)null);
                });

            modelBuilder.Entity("Catalog.Infrastructure.EntityFramework.ReadModel.PlanAlimentario.DiaDelPlanReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedAt");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isDeleted");

                    b.Property<int>("NumeroDia")
                        .HasColumnType("integer")
                        .HasColumnName("numeroDia");

                    b.Property<Guid>("PlanAlimentarioId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("PlanAlimentarioId");

                    b.ToTable("DiaDelPlan", (string)null);
                });

            modelBuilder.Entity("Catalog.Infrastructure.EntityFramework.ReadModel.PlanAlimentario.PlanAlimentarioReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ComidasPorDia")
                        .HasColumnType("integer")
                        .HasColumnName("comidasPorDia");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedAt");

                    b.Property<string>("DuracionTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("duracion");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isDeleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("PlanAlimentario", (string)null);
                });

            modelBuilder.Entity("Catalog.Infrastructure.EntityFramework.ReadModel.PlanAlimentario.RecetaAsignadaReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("RacionCantidad")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("racionCantidad");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uuid")
                        .HasColumnName("recetaId");

                    b.Property<Guid>("TiempoDeComidaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TiempoDeComidaId");

                    b.ToTable("AsignacionReceta", (string)null);
                });

            modelBuilder.Entity("Catalog.Infrastructure.EntityFramework.ReadModel.PlanAlimentario.TiempoDeComidaReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedAt");

                    b.Property<Guid>("DiaDelPlanId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isDeleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("DiaDelPlanId");

                    b.ToTable("TiempoDeComida", (string)null);
                });

            modelBuilder.Entity("Catalog.Infrastructure.EntityFramework.ReadModel.Receta.IngredienteRecetaReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlimentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("alimentoId");

                    b.Property<decimal>("PorcionCantidad")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("porcionCantidad");

                    b.Property<Guid>("RecetaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RecetaId");

                    b.ToTable("IngredienteReceta", (string)null);
                });

            modelBuilder.Entity("Catalog.Infrastructure.EntityFramework.ReadModel.Receta.RecetaReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdAt");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletedAt");

                    b.Property<string>("Instrucciones")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("instrucciones");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isDeleted");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.ToTable("Receta", (string)null);
                });

            modelBuilder.Entity("Catalog.Infrastructure.EntityFramework.ReadModel.PlanAlimentario.DiaDelPlanReadModel", b =>
                {
                    b.HasOne("Catalog.Infrastructure.EntityFramework.ReadModel.PlanAlimentario.PlanAlimentarioReadModel", "PlanAlimentario")
                        .WithMany("DiasDelPlan")
                        .HasForeignKey("PlanAlimentarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanAlimentario");
                });

            modelBuilder.Entity("Catalog.Infrastructure.EntityFramework.ReadModel.PlanAlimentario.RecetaAsignadaReadModel", b =>
                {
                    b.HasOne("Catalog.Infrastructure.EntityFramework.ReadModel.PlanAlimentario.TiempoDeComidaReadModel", "TiempoDeComida")
                        .WithMany("RecetasAsignadas")
                        .HasForeignKey("TiempoDeComidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TiempoDeComida");
                });

            modelBuilder.Entity("Catalog.Infrastructure.EntityFramework.ReadModel.PlanAlimentario.TiempoDeComidaReadModel", b =>
                {
                    b.HasOne("Catalog.Infrastructure.EntityFramework.ReadModel.PlanAlimentario.DiaDelPlanReadModel", "DiaDelPlan")
                        .WithMany("TiemposDeComida")
                        .HasForeignKey("DiaDelPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaDelPlan");
                });

            modelBuilder.Entity("Catalog.Infrastructure.EntityFramework.ReadModel.Receta.IngredienteRecetaReadModel", b =>
                {
                    b.HasOne("Catalog.Infrastructure.EntityFramework.ReadModel.Receta.RecetaReadModel", "Receta")
                        .WithMany("Ingredientes")
                        .HasForeignKey("RecetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Receta");
                });

            modelBuilder.Entity("Catalog.Infrastructure.EntityFramework.ReadModel.PlanAlimentario.DiaDelPlanReadModel", b =>
                {
                    b.Navigation("TiemposDeComida");
                });

            modelBuilder.Entity("Catalog.Infrastructure.EntityFramework.ReadModel.PlanAlimentario.PlanAlimentarioReadModel", b =>
                {
                    b.Navigation("DiasDelPlan");
                });

            modelBuilder.Entity("Catalog.Infrastructure.EntityFramework.ReadModel.PlanAlimentario.TiempoDeComidaReadModel", b =>
                {
                    b.Navigation("RecetasAsignadas");
                });

            modelBuilder.Entity("Catalog.Infrastructure.EntityFramework.ReadModel.Receta.RecetaReadModel", b =>
                {
                    b.Navigation("Ingredientes");
                });
#pragma warning restore 612, 618
        }
    }
}
